local Data = LEMON.API.HelperData

/*---------------------------------------------------------------------------
	Total functions: 504
	Total events: 12
	
	Documented functions: 92
	Documented events: 0
	
	Undocumented functions: 412
	Undocumented events: 12
	
	Generated at: 07/22/13 15:01:54
---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------
	Events
---------------------------------------------------------------------------*/

// F
Data["final<>"] = ""

// K
Data["keypress<n>"] = ""
Data["keyrelease<n>"] = ""

// L
Data["loadFromDupe<p>"] = ""

// P
Data["playerChat<es s>"] = ""
Data["playerJoin<e>"] = ""
Data["playerQuit<e>"] = ""

// R
Data["receiveBuffer<sep>"] = ""

// S
Data["saveToDupe< p>"] = ""

// T
Data["think<>"] = ""
Data["tick<>"] = ""
Data["trigger<s>"] = ""

/*---------------------------------------------------------------------------
	Functions
---------------------------------------------------------------------------*/

// A
Data["aabbMax(e: v)"] = ""
Data["aabbMin(e: v)"] = ""
Data["abs(n n)"] = ""
Data["acos(n n)"] = ""
Data["acosr(n n)"] = ""
Data["aimEntity(e: e)"] = ""
Data["aimNormal(e: v)"] = ""
Data["aimPos(e: v)"] = ""
Data["alpha(c: n)"] = "Gets the alpha of a angle"
Data["ang(e: a)"] = ""
Data["ang(nnn a)"] = "Creates a angle"
Data["angVel(e: a)"] = ""
Data["angnorm(a a)"] = ""
Data["applyAngForce(e:a)"] = ""
Data["applyForce(e:v)"] = ""
Data["applyOffsetForce(e:vv)"] = ""
Data["armor(e: n)"] = ""
Data["asin(n n)"] = ""
Data["asinr(n n)"] = ""
Data["atan(n n)"] = ""
Data["atan(nn n)"] = ""
Data["atanr(n n)"] = ""
Data["atanr(nn n)"] = ""

// B
Data["bearing(e:v n)"] = ""
Data["bearing(vav n)"] = ""
Data["blue(c: n)"] = "Gets the blue of a angle"
Data["boxCenter(e: v)"] = ""
Data["boxMax(e: v)"] = ""
Data["boxMin(e: v)"] = ""
Data["boxSize(e: v)"] = ""
Data["buffer( p)"] = ""

// C
Data["cbrt(n n)"] = ""
Data["ceil(n n)"] = ""
Data["ceil(nn n)"] = ""
Data["ceil(v v)"] = ""
Data["ceil(vn v)"] = ""
Data["clamp(nnn n)"] = ""
Data["clamp(vvv v)"] = ""
Data["class(e: s)"] = ""
Data["clearFilter(xtr)"] = ""
Data["color(e:c)"] = ""
Data["color(h:c)"] = ""
Data["color(nnn c)"] = "Creates a color"
Data["color(nnnn c)"] = "Creates a color"
Data["copy(t: t)"] = ""
Data["cos(n n)"] = ""
Data["cosh(n n)"] = ""
Data["coshr(n n)"] = ""
Data["cosr(n n)"] = ""
Data["cot(n n)"] = ""
Data["coth(n n)"] = ""
Data["cothr(n n)"] = ""
Data["cotr(n n)"] = ""
Data["count(t: n)"] = ""
Data["cross(v:v v)"] = ""
Data["cross(xv2:v xv2)"] = ""
Data["csc(n n)"] = ""
Data["csch(n n)"] = ""
Data["cschr(n n)"] = ""
Data["cscr(n n)"] = ""
Data["curTime( n)"] = ""

// D
Data["distance(v:v n)"] = "Get the distance between vectors."
Data["distance(xv2:v n)"] = "Get the distance between vectors."
Data["distance2(v:v n)"] = ""
Data["dot(v:v n)"] = ""
Data["dot(xv2:v n)"] = ""
Data["driver(e: e)"] = ""
Data["duration(xsd: n)"] = ""
Data["duration(xsd:n)"] = ""

// E
Data["elevation(e:v n)"] = ""
Data["elevation(vav n)"] = ""
Data["enableClip(h:nb)"] = ""
Data["enableGravity(e:b)"] = ""
Data["endPos(xtr:v)"] = ""
Data["entity(n e)"] = ""
Data["entity(xsd: s)"] = ""
Data["entity(xtr: e)"] = ""
Data["entity(xwl: e)"] = ""
Data["exists(t:e b)"] = ""
Data["exists(t:n b)"] = ""
Data["exists(t:s b)"] = ""
Data["exp(nn n)"] = ""
Data["explode(s:s t)"] = ""
Data["explodePattern(s:s t)"] = ""
Data["eye(e: v)"] = ""
Data["eyeAngles(e: a)"] = ""
Data["eyeTrace(e: xtr)"] = ""

// F
Data["fade(xsd:n)"] = ""
Data["fade(xsd:nn)"] = ""
Data["filter(xtr:e)"] = ""
Data["find(s:s n)"] = ""
Data["find(s:sn n)"] = ""
Data["findByClass(s t)"] = ""
Data["findByModel(s t)"] = ""
Data["findInBox(vv t)"] = ""
Data["findInCone(vvna t)"] = ""
Data["findInSphere(vn t)"] = ""
Data["findPattern(s:s n)"] = ""
Data["findPattern(s:sn n)"] = ""
Data["floor(n n)"] = ""
Data["floor(v v)"] = ""
Data["forward(a: a)"] = ""
Data["frac(n n)"] = ""
Data["fraction(xtr: n)"] = ""
Data["fractionLeftSolid(xtr: n)"] = ""
Data["freeze(e:b)"] = ""

// G
Data["gateName( s)"] = ""
Data["gateName(s)"] = ""
Data["getColor(e: c)"] = ""
Data["getColor(h: c)"] = ""
Data["getConstraints(e: t)"] = ""
Data["getHitState(xtr: n)"] = ""
Data["getMaterial(e: s)"] = ""
Data["getParent(h: e)"] = "Gets the parent entity of a hologram"
Data["getParentHolo(h: h)"] = "Gets the parent hologram of a hologram"
Data["getPlayers( t)"] = ""
Data["getScale(h: v)"] = ""
Data["getTable(!: t)"] = "Returns information table of exception."
Data["green(c: n)"] = "Gets the green of a angle"

// H
Data["hardPerf( n)"] = ""
Data["hasConstraints(e: n)"] = ""
Data["hasInput(xwl:s b)"] = ""
Data["hasKinect(e: b)"] = "Returns true if player (E) has a kinect."
Data["hasOutput(xwl:s b)"] = ""
Data["heading(e:v a)"] = ""
Data["heading(vav a)"] = ""
Data["health(e: n)"] = ""
Data["hit(xtr: b)"] = ""
Data["hitAll(xtr:)"] = ""
Data["hitAuxilory(xtr:b)"] = ""
Data["hitBone(xtr: n)"] = ""
Data["hitBox(xtr: n)"] = ""
Data["hitDebris(xtr:b)"] = ""
Data["hitDetail(xtr:b)"] = ""
Data["hitGrate(xtr:b)"] = ""
Data["hitGroup(xtr: n)"] = ""
Data["hitHitboxes(xtr:b)"] = ""
Data["hitLadders(xtr:b)"] = ""
Data["hitMaterial(xtr: n)"] = ""
Data["hitMoveable(xtr:b)"] = ""
Data["hitNPC(xtr:b)"] = ""
Data["hitNPCClip(xtr:b)"] = ""
Data["hitNoDraw(xtr: b)"] = ""
Data["hitNonWorld(xtr: b)"] = ""
Data["hitNormal(xtr: v)"] = ""
Data["hitOpaque(xtr:b)"] = ""
Data["hitOrigin(xtr:b)"] = ""
Data["hitPlayerClip(xtr:b)"] = ""
Data["hitPortal(xtr:b)"] = ""
Data["hitPos(xtr: v)"] = ""
Data["hitSky(xtr: b)"] = ""
Data["hitSlime(xtr:b)"] = ""
Data["hitSolid(xtr:b)"] = ""
Data["hitTexture(xtr: s)"] = ""
Data["hitTranslucent(xtr:b)"] = ""
Data["hitWater(xtr:b)"] = ""
Data["hitWindows(xtr:b)"] = ""
Data["hitWorld(xtr: b)"] = ""
Data["hologram( h)"] = ""
Data["hologram(s h)"] = ""
Data["hologram(sv h)"] = ""
Data["holograms( t)"] = ""
Data["hsv2rgb(c: c)"] = ""
Data["hsv2rgb(nnn c)"] = ""
Data["httpPostRequest(stff)"] = ""
Data["httpRequest(sff)"] = ""

// I
Data["ignoreNoDraw(xtr:b)"] = ""
Data["inNoclip(e: b)"] = ""
Data["index(s:n s)"] = ""
Data["inertia(e: v)"] = ""
Data["inertiaA(e: a)"] = "Shifts vector inertia into angular form."
Data["inputType(xwl:s s)"] = ""
Data["inrange(aaa b)"] = ""
Data["inrange(nnn n)"] = ""
Data["inrange(vvv b)"] = ""
Data["insert(t:!)"] = ""
Data["insert(t:?)"] = ""
Data["insert(t:a)"] = ""
Data["insert(t:b)"] = ""
Data["insert(t:c)"] = ""
Data["insert(t:e)"] = ""
Data["insert(t:f)"] = ""
Data["insert(t:h)"] = ""
Data["insert(t:n!)"] = ""
Data["insert(t:n)"] = ""
Data["insert(t:n?)"] = ""
Data["insert(t:na)"] = ""
Data["insert(t:nb)"] = ""
Data["insert(t:nc)"] = ""
Data["insert(t:ne)"] = ""
Data["insert(t:nf)"] = ""
Data["insert(t:nh)"] = ""
Data["insert(t:nn)"] = ""
Data["insert(t:np)"] = ""
Data["insert(t:ns)"] = ""
Data["insert(t:nt)"] = ""
Data["insert(t:nv)"] = ""
Data["insert(t:nxsd)"] = ""
Data["insert(t:nxtr)"] = ""
Data["insert(t:nxv2)"] = ""
Data["insert(t:nxwl)"] = ""
Data["insert(t:p)"] = ""
Data["insert(t:s)"] = ""
Data["insert(t:t)"] = ""
Data["insert(t:v)"] = ""
Data["insert(t:xsd)"] = ""
Data["insert(t:xtr)"] = ""
Data["insert(t:xv2)"] = ""
Data["insert(t:xwl)"] = ""
Data["int(n n)"] = ""
Data["isAdmin(e: b)"] = ""
Data["isConstrained(e: b)"] = ""
Data["isFrozen(e: b)"] = ""
Data["isHiSpeed(xwl: b)"] = ""
Data["isHologram(e: b)"] = ""
Data["isNPC(e: b)"] = ""
Data["isOnFire(e: b)"] = ""
Data["isOnGround(e: b)"] = ""
Data["isPlayer(e: b)"] = ""
Data["isPlayerHolding(e: b)"] = ""
Data["isPlaying(xsd: b)"] = ""
Data["isSuperAdmin(e: b)"] = ""
Data["isUnderWater(e: b)"] = ""
Data["isValid(e: b)"] = ""
Data["isVehicle(e: b)"] = ""
Data["isWeapon(e: b)"] = ""
Data["isWeldedTo(e: e)"] = ""
Data["isWorld(e: b)"] = ""

Data["include(s)"] = "Include a file."
Data["include(sb)"] = "Include a file."

// K
Data["kinectActive(e: b)"] = "Returns true if player's (E) kinect is active."
Data["kinectHead(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectHip(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectLeftAnkle(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectLeftElbow(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectLeftFoot(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectLeftHand(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectLeftHip(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectLeftKnee(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectLeftShoulder(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectLeftWrist(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectRightAnkle(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectRightElbow(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectRightFoot(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectRightHand(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectRightHip(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectRightKnee(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectRightShoulder(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectRightWrist(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectShoulder(e: v)"] = "Gets a position from the players motion sensor."
Data["kinectSpine(e: v)"] = "Gets a position from the players motion sensor."

// L
Data["left(s:n s)"] = ""
Data["leftClick(e: b)"] = ""
Data["length(s: n)"] = "Returns the length of a string"
Data["length(v: n)"] = "Get the lengh of a vector."
Data["length(xv2: n)"] = "Get the lengh of a vector."
Data["length2(v: n)"] = ""
Data["level(xsd: n)"] = ""
Data["level(xsd:n)"] = ""
Data["ln(n n)"] = ""
Data["log(nn n)"] = ""
Data["log10(n n)"] = ""
Data["log2(n n)"] = ""
Data["lower(s: s)"] = ""

// M
Data["map( s)"] = ""
Data["mass(e: n)"] = ""
Data["massCenter(e: v)"] = ""
Data["massCenterWorld(e: v)"] = ""
Data["matchFirst(s:s s)"] = ""
Data["matchFirst(s:sn s)"] = ""
Data["matchPattern(s:s t)"] = ""
Data["matchPattern(s:sn t)"] = ""
Data["math.Clamp(aaa a)"] = ""
Data["max(nn n)"] = ""
Data["max(nnn n)"] = ""
Data["max(nnnn n)"] = ""
Data["max(nnnnn n)"] = ""
Data["maxHologramClips( n)"] = ""
Data["maxHolograms( n)"] = ""
Data["maxPerf( n)"] = ""
Data["message(!: s)"] = "Returns the current exceptions message"
Data["min(nn n)"] = ""
Data["min(nnn n)"] = ""
Data["min(nnnn n)"] = ""
Data["min(nnnnn n)"] = ""
Data["mix(aan a)"] = "Linearly interpolate between two angles"
Data["mix(nnn n)"] = "Linearly interpolate between two numbers"
Data["mix(vvn v)"] = "Linearly interpolate between two vectors"
Data["mix(xv2xv2n xv2)"] = "Linearly interpolate between two 2D vectors"
Data["model(e: s)"] = ""

// N
Data["name(e: s)"] = ""
Data["normal(xtr: v)"] = ""
Data["normalized(v: v)"] = ""
Data["normalized(xv2: xv2)"] = ""

// O
Data["outputType(xwl:s s)"] = ""
Data["owner( e)"] = "Gets the owner of the executing lemongate."
Data["owner(e: b)"] = ""

// P
Data["p(a: n)"] = "Gets the pitch of a angle"
Data["parent(e:e)"] = "Sets the parent of a entity"
Data["parent(h:e)"] = "Sets the parent of a hologram"
Data["passenger(e: e)"] = ""
Data["path(xsd: s)"] = ""
Data["perf( n)"] = ""
Data["pi( n)"] = ""
Data["ping(e: n)"] = ""
Data["pitch(xsd: n)"] = ""
Data["pitch(xsd:n)"] = ""
Data["play(xsd:)"] = ""
Data["play(xsd:n)"] = ""
Data["pos(e: v)"] = ""
Data["propcore( t)"] = ""
Data["pushClip(h:nvv)"] = ""

// R
Data["r(a: n)"] = "Gets the roll of a angle"
Data["radius(e: n)"] = ""
Data["random( n)"] = ""
Data["random(n n)"] = ""
Data["readAngle(p: a)"] = ""
Data["readArray(xwl:nn t)"] = ""
Data["readCell(xwl:n n)"] = ""
Data["readEntity(p: e)"] = ""
Data["readNumber(p: n)"] = ""
Data["readPos(p n)"] = ""
Data["readString(p: s)"] = ""
Data["readVector(p: v)"] = ""
Data["red(c: n)"] = "Gets the red of a angle"
Data["remove(e:)"] = ""
Data["remove(h:)"] = ""
Data["remove(t:e)"] = ""
Data["remove(t:n)"] = ""
Data["remove(t:s)"] = ""
Data["removeClip(h:n)"] = ""
Data["repeat(s:n s)"] = ""
Data["replace(s:ss n)"] = ""
Data["replacePattern(s:ss s)"] = ""
Data["restart(xsd:)"] = ""
Data["rgb2hsv(c: c)"] = ""
Data["rgb2hsv(nnn c)"] = ""
Data["right(a: a)"] = ""
Data["right(s:n s)"] = ""
Data["rightClick(e: b)"] = ""
Data["root(nn n)"] = ""
Data["rotate(v:a v)"] = ""
Data["round(n n)"] = ""
Data["round(nn n)"] = ""
Data["round(v v)"] = ""
Data["round(vn v)"] = ""

// S
Data["scale(h:v)"] = ""
Data["scaleUnits(h:v)"] = ""
Data["sec(n n)"] = ""
Data["sech(n n)"] = ""
Data["sechr(n n)"] = ""
Data["secr(n n)"] = ""
Data["self( e)"] = "Gets the entity of the executing lemongate."
Data["selfDestruct( e)"] = ""
Data["send(p:se)"] = ""
Data["setAlpha(c:n c)"] = "Sets the alpha of a angle"
Data["setAng(e:a)"] = ""
Data["setAng(h:a)"] = ""
Data["setBlue(c:n c)"] = "Sets the blue of a angle"
Data["setColor(e:c)"] = ""
Data["setGreen(c:n c)"] = "Sets the green of a angle"
Data["setHitState(xtr:n)"] = ""
Data["setMaterial(e:s)"] = ""
Data["setModel(h:s)"] = ""
Data["setNotSolid(e:b)"] = ""
Data["setPitch(a:n a)"] = "Sets the pitch of a angle"
Data["setPos(e:v)"] = ""
Data["setPos(h:v)"] = ""
Data["setRed(c:n c)"] = "Sets the red of a angle"
Data["setRoll(a:n a)"] = "Sets the roll of a angle"
Data["setX(v:n v)"] = "Sets the X of a vector"
Data["setX(xv2:n xv2)"] = "Sets the X of a vector"
Data["setY(v:n v)"] = "Sets the Y of a vector"
Data["setY(xv2:n xv2)"] = "Sets the Y of a vector"
Data["setYaw(a:n a)"] = "Sets the yaw of a angle"
Data["setZ(v:n v)"] = "Sets the Z of a vector"
Data["shading(h:b)"] = ""
Data["shiftL(a a)"] = ""
Data["shiftL(v v)"] = ""
Data["shiftR(a a)"] = ""
Data["shiftR(v v)"] = ""
Data["shootPos(e: v)"] = ""
Data["sign(n n)"] = ""
Data["sin(n n)"] = ""
Data["sinh(n n)"] = ""
Data["sinhr(n n)"] = ""
Data["sinr(n n)"] = ""
Data["size(t: n)"] = ""
Data["skip(p:)"] = ""
Data["softPerf( n)"] = ""
Data["sound(es xsd)"] = ""
Data["sound(esn xsd)"] = ""
Data["sound(s xsd)"] = ""
Data["sound(sn xsd)"] = ""
Data["sounds( t)"] = ""
Data["spawn(s e)"] = ""
Data["spawn(sb e)"] = ""
Data["spawnedProps( t)"] = ""
Data["sqrt(n n)"] = ""
Data["startKinect(e:)"] = "Activates a players motion sensor."
Data["startPos(xtr:v)"] = ""
Data["startSolid(xtr: b)"] = ""
Data["steamID(e: s)"] = ""
Data["stop(xsd:)"] = ""
Data["sub(s:n s)"] = ""
Data["sub(s:nn s)"] = ""

// T
Data["tan(n n)"] = ""
Data["tanh(n n)"] = ""
Data["tanhr(n n)"] = ""
Data["tanr(n n)"] = ""
Data["tau( n)"] = ""
Data["throw(s)"] = "Throws a user exception with a message."
Data["throw(st)"] = "Throws a user exception with a message with a table."
Data["timeConnected(e: n)"] = ""
Data["timerAdjust(snn)"] = ""
Data["timerCreate(snnf)"] = ""
Data["timerPause(s n)"] = ""
Data["timerRemove(s)"] = ""
Data["timerStart(s n)"] = ""
Data["timerStatus(s n)"] = ""
Data["timerStop(s n)"] = ""
Data["timerUnpause(s n)"] = ""
Data["toAngle(v: a)"] = ""
Data["toAngle(v:v a)"] = ""
Data["toByte(s n)"] = ""
Data["toChar(n s)"] = ""
Data["toDeg(n n)"] = ""
Data["toLocal(e:a a)"] = ""
Data["toLocal(e:v v)"] = ""
Data["toLocal(vava v)"] = ""
Data["toLocalAngle(vava v)"] = ""
Data["toRad(n n)"] = ""
Data["toString(c: s)"] = ""
Data["toWorld(e:a a)"] = ""
Data["toWorld(e:v v)"] = ""
Data["toWorld(vava v)"] = ""
Data["toWorldAngle(vava v)"] = ""
Data["tostring(? s)"] = ""
Data["trace( xtr)"] = ""
Data["trace(!: t)"] = "Returns a table of traces on the stack."
Data["trace(!:n t)"] = "Returns a trace at stack position N"
Data["trace(vv xtr)"] = ""
Data["trace(vvn xtr)"] = ""
Data["trim(s: s)"] = ""
Data["trim(s:s s)"] = ""
Data["trimLeft(s:s s)"] = ""
Data["trimRight(s:s s)"] = ""
Data["type(! s)"] = "A usless function that ways returns \"exception\""
Data["type(!: s)"] = "Returns the true type of an Exception"
Data["type(? s)"] = "A usless function that ways returns \"variant\""
Data["type(a s)"] = "A usless function that ways returns \"angle\""
Data["type(b s)"] = "A usless function that ways returns \"boolean\""
Data["type(c s)"] = "A usless function that ways returns \"color\""
Data["type(e s)"] = "A usless function that ways returns \"entity\""
Data["type(f s)"] = "A usless function that ways returns \"function\""
Data["type(h s)"] = "A usless function that ways returns \"hologram\""
Data["type(n s)"] = "A usless function that ways returns \"number\""
Data["type(p s)"] = "A usless function that ways returns \"buffer\""
Data["type(p: s)"] = ""
Data["type(p:n s)"] = ""
Data["type(s s)"] = "A usless function that ways returns \"string\""
Data["type(t s)"] = "A usless function that ways returns \"table\""
Data["type(t:e s)"] = ""
Data["type(t:n s)"] = ""
Data["type(t:s s)"] = ""
Data["type(v s)"] = "A usless function that ways returns \"vector\""
Data["type(xsd s)"] = "A usless function that ways returns \"sound\""
Data["type(xtr s)"] = "A usless function that ways returns \"trace\""
Data["type(xv2 s)"] = "A usless function that ways returns \"vector2\""
Data["type(xwl s)"] = "A usless function that ways returns \"wirelink\""

// U
Data["up(a: a)"] = ""
Data["update(xtr:)"] = ""
Data["upper(s: s)"] = ""
Data["useLineOfSight(xtr:b)"] = ""

// V
Data["vec(nnn v)"] = "Creates a 3 dimentional vector."
Data["vec2(nn xv2)"] = "Creates a 2 dimentional vector."
Data["vehicle(e: e)"] = ""
Data["vel(e: v)"] = ""
Data["visible(h:b)"] = ""
Data["voidEntity( e)"] = ""
Data["volume(xsd: n)"] = ""
Data["volume(xsd:n)"] = ""

// W
Data["writeAngle(p:a)"] = ""
Data["writeCell(xwl:nn b)"] = ""
Data["writeEntity(p:e)"] = ""
Data["writeNumber(p:n)"] = ""
Data["writePos(p n)"] = ""
Data["writeString(p:s)"] = ""
Data["writeString(xwl:snn)"] = ""
Data["writeString(xwl:snnc)"] = ""
Data["writeString(xwl:snncc)"] = ""
Data["writeString(xwl:snnccb)"] = ""
Data["writeString(xwl:snncn)"] = ""
Data["writeString(xwl:snncnb)"] = ""
Data["writeString(xwl:snnn)"] = ""
Data["writeString(xwl:snnnc)"] = ""
Data["writeString(xwl:snnncb)"] = ""
Data["writeString(xwl:snnnn)"] = ""
Data["writeString(xwl:snnnnb)"] = ""
Data["writeVector(p:v)"] = ""

// X
Data["x(v: n)"] = "Gets the X of a vector"
Data["x(xv2: n)"] = "Gets the X of a vector"

// Y
Data["y(a: n)"] = "Gets the yaw of a angle"
Data["y(v: n)"] = "Gets the Z of a vector"
Data["y(xv2: n)"] = "Gets the Z of a vector"

// Z
Data["z(v: n)"] = "Gets the Z of a vector"