LemonGate.HelperFunctionData = LemonGate.HelperFunctionData or { } 
local Data = LemonGate.HelperFunctionData

/*---------------------------------------------------------------------------
	Total functions: 611
	Total events: 9
	
	Documented functions: 23
	Documented events: 0
	
	Undocumented functions: 588
	Undocumented events: 9
	
	Generated at: 03/07/13 21:37:33
---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------
	Events
---------------------------------------------------------------------------*/

// F
Data["final<>"] = ""

// K
Data["keypress<n>"] = ""
Data["keyrelease<n>"] = ""

// P
Data["playerChat<es s>"] = ""
Data["playerJoin<e>"] = ""
Data["playerQuit<e>"] = ""

// T
Data["think<>"] = ""
Data["tick<>"] = ""
Data["trigger<s>"] = ""

/*---------------------------------------------------------------------------
	Functions
---------------------------------------------------------------------------*/

// A
Data["a(c: n)"] = ""
Data["aabbMax(e: v)"] = ""
Data["aabbMin(e: v)"] = ""
Data["abs(n n)"] = ""
Data["acos(n n)"] = ""
Data["acosr(n n)"] = ""
Data["adj(m2 m2)"] = ""
Data["adj(m3 m3)"] = ""
Data["aimEntity(e: e)"] = ""
Data["aimNormal(e: v)"] = ""
Data["aimPos(e: v)"] = ""
Data["ang(e: a)"] = ""
Data["ang(h: a)"] = ""
Data["ang(nnn a)"] = ""
Data["angVel(e: a)"] = ""
Data["angnorm(a a)"] = ""
Data["applyAngForce(e:a)"] = ""
Data["applyForce(e:v)"] = ""
Data["applyOffsetForce(e:vv)"] = ""
Data["armor(e: n)"] = ""
Data["asin(n n)"] = ""
Data["asinr(n n)"] = ""
Data["atan(n n)"] = ""
Data["atan(nn n)"] = ""
Data["atanr(n n)"] = ""
Data["atanr(nn n)"] = ""

// B
Data["b(c: n)"] = ""
Data["bearing(e:v n)"] = ""
Data["bearing(vav n)"] = ""
Data["boxCenter(e: v)"] = ""
Data["boxCenterWorld(e: v)"] = ""
Data["boxMax(e: v)"] = ""
Data["boxMin(e: v)"] = ""
Data["boxSize(e: v)"] = ""

// C
Data["cbrt(n n)"] = ""
Data["ceil(a a)"] = ""
Data["ceil(an a)"] = ""
Data["ceil(n n)"] = ""
Data["ceil(nn n)"] = ""
Data["ceil(v v)"] = ""
Data["ceil(vn v)"] = ""
Data["clamp(aaa a)"] = ""
Data["clamp(nnn n)"] = ""
Data["clamp(vvv v)"] = ""
Data["class(e: s)"] = ""
Data["close(xfl:)"] = ""
Data["color(h:c)"] = ""
Data["color(nnn c)"] = ""
Data["color(nnnn c)"] = ""
Data["column(m2:n v2)"] = ""
Data["column(m3:n v)"] = ""
Data["copy(t: t)"] = ""
Data["cos(n n)"] = ""
Data["cosh(n n)"] = ""
Data["coshr(n n)"] = ""
Data["cosr(n n)"] = ""
Data["cot(n n)"] = ""
Data["coth(n n)"] = ""
Data["cothr(n n)"] = ""
Data["cotr(n n)"] = ""
Data["count(t: n)"] = ""
Data["createDir(s)"] = ""
Data["createDir(sf)"] = ""
Data["cross(v2:v2 n)"] = ""
Data["cross(v:v v)"] = ""
Data["csc(n n)"] = ""
Data["csch(n n)"] = ""
Data["cschr(n n)"] = ""
Data["cscr(n n)"] = ""
Data["curTime( n)"] = "Returns the server current uptime."

// D
Data["debugTrace( t)"] = ""
Data["debugTrace(n t)"] = ""
Data["det(m2 n)"] = ""
Data["det(m3 n)"] = ""
Data["diagonal(m2 v2)"] = ""
Data["diagonal(m3 v)"] = ""
Data["distance(v2:v2 n)"] = ""
Data["distance(v:v n)"] = ""
Data["distance2(v2:v2 n)"] = ""
Data["distance2(v:v n)"] = ""
Data["dot(v2:v2 n)"] = ""
Data["dot(v:v n)"] = ""
Data["driver(e: e)"] = ""
Data["duration(sd: n)"] = ""
Data["duration(sd:n)"] = ""

// E
Data["egp3DTracker(wl:nv2)"] = ""
Data["egpAlign(wl:nn)"] = ""
Data["egpAlign(wl:nnn)"] = ""
Data["egpAlpha(wl:n n)"] = ""
Data["egpAlpha(wl:nn)"] = ""
Data["egpAngle(wl:n n)"] = ""
Data["egpAngle(wl:nn)"] = ""
Data["egpAngle(wl:nv2v2n)"] = ""
Data["egpBox(wl:nv2v2)"] = ""
Data["egpBoxOutline(wl:nv2v2)"] = ""
Data["egpCanSendUmsg( n)"] = ""
Data["egpCircle(wl:nv2v2)"] = ""
Data["egpCircleOutline(wl:nv2v2)"] = ""
Data["egpClear(wl:)"] = ""
Data["egpClearQueue( n)"] = ""
Data["egpColor(wl:n c)"] = ""
Data["egpColor(wl:nc)"] = ""
Data["egpCopy(wl:nn)"] = ""
Data["egpCursor(wl:e v2)"] = ""
Data["egpDrawTopLeft(wl:n)"] = ""
Data["egpFidelity(wl:n n)"] = ""
Data["egpFidelity(wl:nn)"] = ""
Data["egpFont(wl:ns)"] = ""
Data["egpFont(wl:nsn)"] = ""
Data["egpHasObject(wl:n n)"] = ""
Data["egpHudToggle(wl:)"] = ""
Data["egpLine(wl:nv2v2)"] = ""
Data["egpLoadFrame(wl:n)"] = ""
Data["egpLoadFrame(wl:s)"] = ""
Data["egpMaterial(wl:n s)"] = ""
Data["egpMaterial(wl:ns)"] = ""
Data["egpMaterialFromScreen(wl:ne)"] = ""
Data["egpMaxObjects( n)"] = ""
Data["egpMaxUmsgPerSecond( n)"] = ""
Data["egpNumObjects(wl: n)"] = ""
Data["egpOrder(wl:n n)"] = ""
Data["egpOrder(wl:nn)"] = ""
Data["egpParent(wl:n n)"] = ""
Data["egpParent(wl:ne)"] = ""
Data["egpParent(wl:nn)"] = ""
Data["egpParentToCursor(wl:n)"] = ""
Data["egpPos(wl:n v2)"] = ""
Data["egpPos(wl:nv2)"] = ""
Data["egpQueue( n)"] = ""
Data["egpQueueClk( n)"] = ""
Data["egpQueueClk(e n)"] = ""
Data["egpQueueClk(wl n)"] = ""
Data["egpQueueClkPly(e n)"] = ""
Data["egpQueuePlayer( e)"] = ""
Data["egpQueueScreen( e)"] = ""
Data["egpQueueScreenWirelink( wl)"] = ""
Data["egpRadius(wl:n n)"] = ""
Data["egpRadius(wl:nn)"] = ""
Data["egpRemove(wl:n)"] = ""
Data["egpResolution(wl:v2v2)"] = ""
Data["egpRoundedBox(wl:nv2v2)"] = ""
Data["egpRoundedBoxOutline(wl:nv2v2)"] = ""
Data["egpRunOnQueue(wl:n)"] = ""
Data["egpSaveFrame(wl:n)"] = ""
Data["egpSaveFrame(wl:s)"] = ""
Data["egpScale(wl:v2v2)"] = ""
Data["egpScrH(e n)"] = ""
Data["egpScrSize(e v2)"] = ""
Data["egpScrW(e n)"] = ""
Data["egpSetText(wl:ns)"] = ""
Data["egpSize(wl:n v2)"] = ""
Data["egpSize(wl:nn)"] = ""
Data["egpSize(wl:nv2)"] = ""
Data["egpSizeNum(wl:n n)"] = ""
Data["egpText(wl:nsv2)"] = ""
Data["egpTextLayout(wl:nsv2v2)"] = ""
Data["egpToWorld(wl:v2 v)"] = ""
Data["egpTrackerParent(wl:n e)"] = ""
Data["egpTriangle(wl:nv2v2v2)"] = ""
Data["egpTriangleOutline(wl:nv2v2v2)"] = ""
Data["egpUnParent(wl:n)"] = ""
Data["egpWedge(wl:nv2v2)"] = ""
Data["egpWedgeOutline(wl:nv2v2)"] = ""
Data["element(m2:nn n)"] = ""
Data["element(m3:nn n)"] = ""
Data["elevation(e:v n)"] = ""
Data["elevation(vav n)"] = ""
Data["enableClip(h:nn)"] = ""
Data["enableGravity(e:n)"] = ""
Data["entity(n e)"] = ""
Data["entity(sd: e)"] = ""
Data["entity(wl: e)"] = ""
Data["exists(t:e n)"] = ""
Data["exists(t:n n)"] = ""
Data["exists(t:s n)"] = ""
Data["exit()"] = "Exits current execution."
Data["exp(n n)"] = ""
Data["explode(s:s t)"] = ""
Data["explodePattern(s:s t)"] = ""
Data["eye(e: v)"] = ""
Data["eyeAngles(e: a)"] = ""
Data["eyeTrace(e: t)"] = "Returns a trace of the player eye."

// F
Data["fade(sd:n)"] = ""
Data["fade(sd:nn)"] = ""
Data["fileDelete(s)"] = ""
Data["fileDelete(sf)"] = ""
Data["fileFind(sf)"] = ""
Data["filePath(xfl: s)"] = ""
Data["find(s:s n)"] = ""
Data["find(s:sn n)"] = ""
Data["findByClass(s t)"] = "Returns a table of all entities of class S."
Data["findByModel(s t)"] = "Returns a table of all entities of model S."
Data["findInBox(vv t)"] = "Returns a table of all entities within inside V1 min and V2 max."
Data["findInCone(vvna t)"] = "Returns a table of all entities within inside a cone."
Data["findInSphere(vn t)"] = "Returns a table of all entities within a distance of N from point V."
Data["findPattern(s:s n)"] = ""
Data["findPattern(s:sn n)"] = ""
Data["floor(a a)"] = ""
Data["floor(n n)"] = ""
Data["floor(v v)"] = ""
Data["forward(a: v)"] = ""
Data["frac(n n)"] = ""
Data["freeze(e:n)"] = ""

// G
Data["g(c: n)"] = ""
Data["gate( e)"] = "Returns the entity of the LemonGate."
Data["gateName( s)"] = "Returns the name of the LemonGate."
Data["gateName(s)"] = "Sets the name of the LemonGate."
Data["getColor(e: c)"] = ""
Data["getColor(h: c)"] = ""
Data["getConstraints(e: t)"] = ""
Data["getMaterial(e: s)"] = ""
Data["getParent(h: h)"] = ""
Data["getParentE(h: e)"] = ""
Data["getPlayers( t)"] = "Returns a table of all the players on the server."
Data["getScale(h: v)"] = ""

// H
Data["hasConstraints(e: n)"] = ""
Data["hasInput(wl:s n)"] = ""
Data["hasOutput(wl:s n)"] = ""
Data["heading(e:v a)"] = ""
Data["heading(vav n)"] = ""
Data["health(e: n)"] = ""
Data["hologram( h)"] = ""
Data["hologram(s h)"] = ""
Data["hologram(sv h)"] = ""
Data["holograms( t)"] = ""
Data["hsv2rgb(c: c)"] = ""
Data["hsv2rgb(nnn c)"] = ""
Data["httpPostRequest(stff)"] = ""
Data["httpRequest(sff)"] = ""

// I
Data["identity( m3)"] = ""
Data["identity2( m2)"] = ""
Data["inNoclip(e: n)"] = ""
Data["inVehicle(e: n)"] = ""
Data["index(s:n s)"] = ""
Data["inputType(wl:s s)"] = ""
Data["inrange(aaa n)"] = ""
Data["inrange(nnn n)"] = ""
Data["inrange(vvv n)"] = ""
Data["insert(t:?)"] = ""
Data["insert(t:?e)"] = ""
Data["insert(t:?n)"] = ""
Data["insert(t:?s)"] = ""
Data["insert(t:a)"] = ""
Data["insert(t:ae)"] = ""
Data["insert(t:an)"] = ""
Data["insert(t:as)"] = ""
Data["insert(t:c)"] = ""
Data["insert(t:ce)"] = ""
Data["insert(t:cn)"] = ""
Data["insert(t:cs)"] = ""
Data["insert(t:e)"] = ""
Data["insert(t:ee)"] = ""
Data["insert(t:en)"] = ""
Data["insert(t:es)"] = ""
Data["insert(t:f)"] = ""
Data["insert(t:fe)"] = ""
Data["insert(t:fn)"] = ""
Data["insert(t:fs)"] = ""
Data["insert(t:h)"] = ""
Data["insert(t:he)"] = ""
Data["insert(t:hn)"] = ""
Data["insert(t:hs)"] = ""
Data["insert(t:m2)"] = ""
Data["insert(t:m2e)"] = ""
Data["insert(t:m2n)"] = ""
Data["insert(t:m2s)"] = ""
Data["insert(t:m3)"] = ""
Data["insert(t:m3e)"] = ""
Data["insert(t:m3n)"] = ""
Data["insert(t:m3s)"] = ""
Data["insert(t:n)"] = ""
Data["insert(t:ne)"] = ""
Data["insert(t:nn)"] = ""
Data["insert(t:ns)"] = ""
Data["insert(t:s)"] = ""
Data["insert(t:sd)"] = ""
Data["insert(t:sde)"] = ""
Data["insert(t:sdn)"] = ""
Data["insert(t:sds)"] = ""
Data["insert(t:se)"] = ""
Data["insert(t:sn)"] = ""
Data["insert(t:ss)"] = ""
Data["insert(t:t)"] = ""
Data["insert(t:te)"] = ""
Data["insert(t:tn)"] = ""
Data["insert(t:ts)"] = ""
Data["insert(t:v)"] = ""
Data["insert(t:v2)"] = ""
Data["insert(t:v2e)"] = ""
Data["insert(t:v2n)"] = ""
Data["insert(t:v2s)"] = ""
Data["insert(t:ve)"] = ""
Data["insert(t:vn)"] = ""
Data["insert(t:vs)"] = ""
Data["insert(t:wl)"] = ""
Data["insert(t:wle)"] = ""
Data["insert(t:wln)"] = ""
Data["insert(t:wls)"] = ""
Data["insert(t:xfl)"] = ""
Data["insert(t:xfle)"] = ""
Data["insert(t:xfln)"] = ""
Data["insert(t:xfls)"] = ""
Data["int(n n)"] = ""
Data["isAdmin(e: n)"] = ""
Data["isConstrained(e: n)"] = ""
Data["isFrozen(e: n)"] = ""
Data["isHiSpeed(wl: n)"] = ""
Data["isHologram(e:)"] = ""
Data["isNPC(e: n)"] = ""
Data["isOnFire(e: n)"] = ""
Data["isOnGround(e: n)"] = ""
Data["isPlayer(e: n)"] = ""
Data["isPlayerHolding(e: n)"] = ""
Data["isPlaying(sd: n)"] = ""
Data["isSuperAdmin(e: n)"] = ""
Data["isUnderWater(e: n)"] = ""
Data["isValid(e: n)"] = ""
Data["isValid(h: n)"] = ""
Data["isVehicle(e: n)"] = ""
Data["isWeapon(e: n)"] = ""
Data["isWeldedTo(e: e)"] = ""
Data["isWorld(e: n)"] = ""

// L
Data["left(s:n s)"] = ""
Data["leftClick(e: n)"] = ""
Data["length(s: n)"] = ""
Data["length(t: n)"] = ""
Data["length(v2: n)"] = ""
Data["length(v: n)"] = ""
Data["length2(v2: n)"] = ""
Data["length2(v: n)"] = ""
Data["level(sd: n)"] = ""
Data["level(sd:n)"] = ""
Data["ln(n n)"] = ""
Data["log(nn n)"] = ""
Data["log10(n n)"] = ""
Data["log2(n n)"] = ""
Data["lower(s: s)"] = ""

// M
Data["mRotation(vn m3)"] = ""
Data["map( s)"] = ""
Data["mass(e: n)"] = ""
Data["massCenter(e: v)"] = ""
Data["massCenterWorld(e: v)"] = ""
Data["matchFirst(s:s s)"] = ""
Data["matchFirst(s:sn s)"] = ""
Data["matchPattern(s:s t)"] = ""
Data["matchPattern(s:sn t)"] = ""
Data["matrix( m3)"] = ""
Data["matrix(a m3)"] = ""
Data["matrix(e m3)"] = ""
Data["matrix(m2 m3)"] = ""
Data["matrix(nnnnnnnnn m3)"] = ""
Data["matrix(vvv m3)"] = ""
Data["matrix2( m2)"] = ""
Data["matrix2(m3 m2)"] = ""
Data["matrix2(nnnn m2)"] = ""
Data["matrix2(v2v2 m2)"] = ""
Data["max(nn n)"] = ""
Data["max(nnn n)"] = ""
Data["max(nnnn n)"] = ""
Data["maxHologramClips( n)"] = ""
Data["maxHolograms( n)"] = ""
Data["maxPerf( n)"] = "Returns the maximum performance points the code can use."
Data["min(nn n)"] = ""
Data["min(nnn n)"] = ""
Data["min(nnnn n)"] = ""
Data["model(e: s)"] = ""

// N
Data["name(e: s)"] = ""
Data["normalized(v2: v2)"] = ""
Data["normalized(v: v)"] = ""

// O
Data["openFile(ss xfl)"] = ""
Data["outputType(wl:s s)"] = ""
Data["owner( e)"] = "Returns the owner of the LemonGate."

// P
Data["p(a: n)"] = ""
Data["parent(e:e)"] = ""
Data["parent(e:h)"] = ""
Data["parent(h:e)"] = ""
Data["parent(h:h)"] = ""
Data["passenger(e: e)"] = ""
Data["path(sd: s)"] = ""
Data["perf( n)"] = "Returns the current used performance points."
Data["perfAvailable( n)"] = ""
Data["perfPer( n)"] = "Returns the percentage of performance points used."
Data["pi( n)"] = ""
Data["ping(e: n)"] = ""
Data["pitch(sd: n)"] = ""
Data["pitch(sd:n)"] = ""
Data["play(sd:)"] = ""
Data["play(sd:n)"] = ""
Data["pos(e: v)"] = ""
Data["pos(h: v)"] = ""
Data["print(...)"] = "Prints all arguments to chat."
Data["propcore( n)"] = ""
Data["propcoreInfo( t)"] = ""
Data["propcoreProps( t)"] = ""
Data["pushClip(h:nvv)"] = ""

// R
Data["r(a: n)"] = ""
Data["r(c: n)"] = ""
Data["radius(e: n)"] = ""
Data["randint(n n)"] = ""
Data["randint(nn n)"] = ""
Data["random( n)"] = ""
Data["random(n n)"] = ""
Data["random(nn n)"] = ""
Data["read(xfl:f)"] = ""
Data["readArray(wl:nn t)"] = ""
Data["readCell(wl:n n)"] = ""
Data["remove(e:)"] = ""
Data["remove(h:)"] = ""
Data["remove(t:e)"] = ""
Data["remove(t:n)"] = ""
Data["remove(t:s)"] = ""
Data["removeClip(h:n)"] = ""
Data["repeat(s:n s)"] = ""
Data["replace(s:ss s)"] = ""
Data["replacePattern(s:ss s)"] = ""
Data["restart(sd:)"] = ""
Data["rgb2hsv(c: c)"] = ""
Data["rgb2hsv(nnn c)"] = ""
Data["right(a: v)"] = ""
Data["right(s:n s)"] = ""
Data["rightClick(e: n)"] = ""
Data["root(nn n)"] = ""
Data["rotate(v:a v)"] = ""
Data["round(a a)"] = ""
Data["round(an a)"] = ""
Data["round(n n)"] = ""
Data["round(nn n)"] = ""
Data["round(v v)"] = ""
Data["round(vn v)"] = ""
Data["row(m2:n v2)"] = ""
Data["row(m3:n v)"] = ""
Data["rowMatrix(vvv m3)"] = ""
Data["rowMatrix2(v2v2 m2)"] = ""

// S
Data["scale(h:v)"] = ""
Data["scaleUnits(h:v)"] = ""
Data["sec(n n)"] = ""
Data["sech(n n)"] = ""
Data["sechr(n n)"] = ""
Data["secr(n n)"] = ""
Data["selfDestruct()"] = "Removes the LemonGate. "
Data["setA(c:n c)"] = ""
Data["setAng(e:a)"] = ""
Data["setAng(h:a)"] = ""
Data["setB(c:n c)"] = ""
Data["setColor(e:c)"] = ""
Data["setColumn(m2:nnn m2)"] = ""
Data["setColumn(m2:nv2 m2)"] = ""
Data["setColumn(m3:nnnn m3)"] = ""
Data["setColumn(m3:nv m3)"] = ""
Data["setDiagonal(m3:nnn m3)"] = ""
Data["setDiagonal(m3:v m3)"] = ""
Data["setElement(m2:nnn m2)"] = ""
Data["setElement(m3:nnn m3)"] = ""
Data["setG(c:n c)"] = ""
Data["setMaterial(e:s)"] = ""
Data["setModel(h:s)"] = ""
Data["setNotSolid(e:n)"] = ""
Data["setP(a:n a)"] = ""
Data["setPos(e:v)"] = ""
Data["setPos(h:v)"] = ""
Data["setR(a:n a)"] = ""
Data["setR(c:n c)"] = ""
Data["setRow(m2:nnn m2)"] = ""
Data["setRow(m2:nv2 m2)"] = ""
Data["setRow(m3:nnnn m3)"] = ""
Data["setRow(m3:nv m3)"] = ""
Data["setX(v2:n)"] = ""
Data["setX(v:n v)"] = ""
Data["setY(a:n a)"] = ""
Data["setY(v2:n)"] = ""
Data["setY(v:n v)"] = ""
Data["setZ(v:n v)"] = ""
Data["shading(h:n)"] = ""
Data["shootPos(e: v)"] = ""
Data["sign(n n)"] = ""
Data["sin(n n)"] = ""
Data["sinh(n n)"] = ""
Data["sinhr(n n)"] = ""
Data["sinr(n n)"] = ""
Data["size(t: n)"] = ""
Data["sound(es sd)"] = ""
Data["sound(esn sd)"] = ""
Data["sound(s sd)"] = ""
Data["sound(sn sd)"] = ""
Data["sounds( t)"] = ""
Data["spawn(s e)"] = ""
Data["spawn(sn e)"] = ""
Data["sqrt(n n)"] = ""
Data["steamID(e: s)"] = ""
Data["stop(sd:)"] = ""
Data["sub(s:n s)"] = ""
Data["sub(s:nn s)"] = ""
Data["swapColumns(m2: m2)"] = ""
Data["swapColumns(m3:nn m3)"] = ""
Data["swapElements(m2:nnnn m2)"] = ""
Data["swapElements(m3:nnnn m3)"] = ""
Data["swapRows(m2: m2)"] = ""
Data["swapRows(m3:nn m3)"] = ""

// T
Data["tan(n n)"] = ""
Data["tanh(n n)"] = ""
Data["tanhr(n n)"] = ""
Data["tanr(n n)"] = ""
Data["time(s n)"] = "Returns the server time in unit S"
Data["timeConnected(e: n)"] = ""
Data["timerAdjust(snn)"] = ""
Data["timerCreate(snnf)"] = ""
Data["timerPause(s n)"] = ""
Data["timerRemove(s)"] = ""
Data["timerStart(s n)"] = ""
Data["timerStatus(s n)"] = ""
Data["timerStop(s n)"] = ""
Data["timerUnpause(s n)"] = ""
Data["toAngle(m3: a)"] = ""
Data["toAngle(v2: n)"] = ""
Data["toAngle(v: a)"] = ""
Data["toAngle(v:v a)"] = ""
Data["toByte(s n)"] = ""
Data["toByte(sn n)"] = ""
Data["toChar(n s)"] = ""
Data["toDeg(n n)"] = ""
Data["toLocal(e:a a)"] = ""
Data["toLocal(e:v v)"] = ""
Data["toLocal(vava v)"] = ""
Data["toLocalAngle(vava a)"] = ""
Data["toNumber(s n)"] = ""
Data["toNumber(s: n)"] = ""
Data["toRad(n n)"] = ""
Data["toString(a s)"] = ""
Data["toString(a: s)"] = ""
Data["toString(e s)"] = ""
Data["toString(e: s)"] = ""
Data["toString(n s)"] = ""
Data["toString(n: s)"] = ""
Data["toString(v s)"] = ""
Data["toString(v2 s)"] = ""
Data["toString(v2: s)"] = ""
Data["toString(v: sd)"] = ""
Data["toWorld(e:a a)"] = ""
Data["toWorld(e:v v)"] = ""
Data["toWorld(vava v)"] = ""
Data["toWorldAngle(vava v)"] = ""
Data["trace(m2 n)"] = ""
Data["trace(m3 n)"] = ""
Data["trace(vv t)"] = "Returns a trace between V1 and V2."
Data["trace(vvn t)"] = "Same as t = trace(vv), but the trace can hit water when N is 1."
Data["trace(vvnt t)"] = "Same as y = trace(vvn), but T is a table of entities to filter."
Data["trace(vvvn t)"] = ""
Data["trace(vvvnt t)"] = ""
Data["traceHull(vvv t)"] = "Returns a hull trace between V1 and V2 where V3 is boxsize."
Data["transpose(m2 m2)"] = ""
Data["transpose(m3 m3)"] = ""
Data["trim(s: s)"] = ""
Data["trim(s:s s)"] = ""
Data["trimLeft(s: s)"] = ""
Data["trimLeft(s:s s)"] = ""
Data["trimRight(s: s)"] = ""
Data["trimRight(s:s s)"] = ""
Data["type(? s)"] = ""
Data["type(a s)"] = ""
Data["type(c s)"] = ""
Data["type(e s)"] = ""
Data["type(f s)"] = ""
Data["type(h s)"] = ""
Data["type(m2 s)"] = ""
Data["type(m3 s)"] = ""
Data["type(n s)"] = ""
Data["type(s s)"] = ""
Data["type(sd s)"] = ""
Data["type(t s)"] = ""
Data["type(t:e s)"] = ""
Data["type(t:n s)"] = ""
Data["type(t:s s)"] = ""
Data["type(v s)"] = ""
Data["type(v2 s)"] = ""
Data["type(wl s)"] = ""
Data["type(xfl s)"] = ""

// U
Data["unparent(e:)"] = ""
Data["up(a: v)"] = ""
Data["upper(s: s)"] = ""

// V
Data["vec(nnn v)"] = ""
Data["vec2(nn v2)"] = ""
Data["vec2(v v2)"] = ""
Data["vehicle(e: e)"] = ""
Data["vel(e: v)"] = ""
Data["visible(h:n)"] = ""
Data["voidEntity( e)"] = ""
Data["volume(sd: n)"] = ""
Data["volume(sd:n)"] = ""

// W
Data["write(xfl:s)"] = ""
Data["write(xfl:sf)"] = ""
Data["writeCell(wl:nn n)"] = ""
Data["writeString(wl:snn)"] = ""
Data["writeString(wl:snnc)"] = ""
Data["writeString(wl:snncc)"] = ""
Data["writeString(wl:snnccn)"] = ""
Data["writeString(wl:snncn)"] = ""
Data["writeString(wl:snncnn)"] = ""
Data["writeString(wl:snnn)"] = ""
Data["writeString(wl:snnnc)"] = ""
Data["writeString(wl:snnncn)"] = ""
Data["writeString(wl:snnnn)"] = ""
Data["writeString(wl:snnnnn)"] = ""

// X
Data["x(m3: v)"] = ""
Data["x(v2: n)"] = ""
Data["x(v: n)"] = ""

// Y
Data["y(a: n)"] = ""
Data["y(m3: v)"] = ""
Data["y(v2: n)"] = ""
Data["y(v: n)"] = ""

// Z
Data["z(m3: v)"] = ""
Data["z(v: n)"] = ""